# Generated by Django 5.1.4 on 2025-01-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='mascotas/')),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
